[package]
name = "mopro-ffi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
name = "mopro_ffi"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[features]
default = ["circom"]
# default = ["gpu-benchmarks"]
# default = ["calc-native-witness"]

# If we enable them here, they should be enabled in mopro-core as well
halo2 = ["mopro-core/halo2"]
circom = ["mopro-core/default"]
dylib = ["mopro-core/dylib", "circom"]
gpu-benchmarks = ["mopro-core/gpu-benchmarks", "circom"]
calc-native-witness = ["mopro-core/calc-native-witness", "circom"]

[dependencies]
mopro-core = { path = "../mopro-core", default-features = false }
uniffi = { version = "0.25", features = ["cli"] }
serde = { version = "1", features = ["derive"] }
bincode = "1"
ark-serialize = { version = "=0.4.1", features = ["derive"] }
num-bigint = { version = "=0.4.3", default-features = false, features = [
    "rand",
] }

# Error handling
thiserror = "=1.0.39"
color-eyre = "=0.6.2"
criterion = "=0.3.6"

[build-dependencies]
uniffi = { version = "0.25", features = ["build"] }

[dev-dependencies]
uniffi = { version = "0.25", features = ["bindgen-tests"] }
# Circom test dependency
ark-bn254 = { version = "=0.4.0" }
# Halo2 test dependency
halo2curves = { git = "https://github.com/privacy-scaling-explorations/halo2curves", tag = "0.3.2" }
