# mopro-config.toml

[build]
# For iOS device_type can be x86_64, simulator, device
ios_device_type = "device" # Options: x86_64, simulator, device
# For Android device_type can be x86_64, x86, arm, arm64
android_device_type = "arm64" # Options: x86_64, x86, arm, arm64

# debug is for Rust library to be in debug mode and release for release mode
# We recommend release mode by default for performance
build_mode = "release" # Options: debug, release

[circuit]
# multiplier2
# dir = "core/circuits/multiplier2"
# name = "multiplier2"
# ptau = "02"                       # ptau to use for trusted setup of circuit, "01" to "27"

# keccak256
dir = "core/circuits/keccak256"
name = "keccak256_256_test"
ptau = "19"

[dylib]
# NOTE: Dylib support is experimental may require some fiddling in iOS
# It is currently only supported for real devices on iOS
use_dylib = true   # Options: true, false
name = "keccak256" # Name of the dylib file, only used if use_dylib is true
