name: Build and Test

on:
    push:
    pull_request:
        types:
            - opened
            - reopened
            - ready_for_review

env:
    CARGO_TERM_COLOR: always

jobs:
    # TODO: Add a job to run clippy
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Check formatting
              run: cargo fmt --all -- --check

    test-ffi:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
            - name: Run FFI circom tests
              # TODO: Fix this custom jar thing
              run: |
                  cd mopro-ffi/
                  curl -L https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar -o jna-5.13.0.jar
                  CLASSPATH=jna-5.13.0.jar cargo test -- --nocapture
            - name: Run FFI halo2 tests
              run: |
                  cd mopro-ffi/
                  cargo test --features halo2 -- halo2 