name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install circom
        run: |
          git clone https://github.com/iden3/circom.git
          cd circom
          cargo build --release
          cargo install --path circom
      - name: Prepare CI
        run: ./scripts/prepare_ci.sh
      - name: Build for iOS
        run: ./scripts/build_ios.sh x86_64 debug
      - name: Build for android
        run: ./scripts/build_android.sh arm64 debug
      - name: Run core tests
        run: cd mopro-core && cargo test -- --nocapture
      - name: Run ffi tests
        run: cd mopro-ffi/ && cargo test -- --nocapture
      - name: Run ios tests
        run: |
          cd mopro-ios/MoproKit/Example
          xcodebuild test -scheme MoproKit-Example -workspace MoproKit.xcworkspace -destination "platform=iOS Simulator,OS=16.2,name=iPhone 14 Pro" 
  lint: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check mopro-core formatting
        run: cd ark-zkey/ && cargo fmt --all -- --check
      - name: Check mopro-core formatting
        run: cd mopro-core/ && cargo fmt --all -- --check
      - name: Check mopro-ffi formatting
        run: cd mopro-ffi/ && cargo fmt --all -- --check
